name: Delete PDF from GitLab

on:
  workflow_dispatch:

jobs:
  delete_old_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1: Eliminar PDF antiguo en GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git config --global user.name "Victor Garcia (GitHub Action)"
          git config --global user.email "victor@example.com"

          git clone https://oauth2:${GITLAB_TOKEN}@gitlab.com/mackonde1/victorgarciads-site.git repo
          cd repo

          if [ -f assets/sources/Publications/Integral/Integraci贸n.pdf ]; then
            rm assets/sources/Publications/Integral/Integraci贸n.pdf
            git add assets/sources/Publications/Integral/Integraci贸n.pdf
            git commit -m "Eliminaci贸n del PDF desde GitHub Actions"
            git push
          else
            echo "El archivo no existe. No hay nada que eliminar."
          fi
